list = []
with open('sample.txt', 'r') as file:
  for line in file.readlines():
    if len(line.split(',')) >= 24:
      d = dict()
      d['data01'] = line.split(',')[0]
      d['data02'] = line.split(',')[1]
      d['data03'] = line.split(',')[2]
      d['data04'] = line.split(',')[3]
      d['data05'] = line.split(',')[4]
      d['data06'] = line.split(',')[5]
      d['data07'] = line.split(',')[6]
      d['data08'] = line.split(',')[7]
      d['data09'] = line.split(',')[8]
      d['data10'] = line.split(',')[9]
      d['data11'] = line.split(',')[10]
      d['data12'] = line.split(',')[11]
      d['data13'] = line.split(',')[12]
      d['data14'] = line.split(',')[13]
      d['data15'] = line.split(',')[14]
      d['data16'] = line.split(',')[15]
      d['data17'] = line.split(',')[16]
      d['data18'] = line.split(',')[17]
      d['data19'] = line.split(',')[18]
      d['data20'] = line.split(',')[19]
      d['data21'] = line.split(',')[20]
      d['data22'] = line.split(',')[21]
      d['data23'] = line.split(',')[22]
      d['data24'] = line.split(',')[23]
      d['data25'] = line.split(',')[24]
      d['data26'] = line.split(',')[25]
      d['data27'] = line.split(',')[26]
      d['data28'] = line.split(',')[27]
      d['data29'] = line.split(',')[28]
      d['data30'] = line.split(',')[29]
      d['data31'] = line.split(',')[30]
      d['data32'] = line.split(',')[31]
      d['data33'] = line.split(',')[32]
      d['data34'] = line.split(',')[33]
      d['data35'] = line.split(',')[34]
      d['data36'] = line.split(',')[35]
      d['data37'] = line.split(',')[36]
      d['data38'] = line.split(',')[37]
      d['data39'] = line.split(',')[38]
      d['data40'] = line.split(',')[39]
      d['data41'] = line.split(',')[40]
      list.append(d)
print(list)
